<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Dirt\Log\Log.csproj" />
    <ProjectReference Include="..\Mud\Mud.csproj" />
  </ItemGroup>

</Project>
