<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Dirt.Log</AssemblyName>
    <PackageId>Dirt.Log</PackageId>
    <Product>Dirt.Log</Product>
    <Version>1.1.0</Version>
    <Authors>Salepate</Authors>
    <Title>Dirt Logger</Title>
    <Description>Framework Logger</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Salepate</Copyright>
    <PackageTags>Dirt.Framework</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
