<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Dirt.Game</AssemblyName>
    <PackageId>Dirt.Game</PackageId>
    <Product>Dirt.Game</Product>
    <Version>1.1.0</Version>
    <Authors>Salepate</Authors>
    <Title>Dirt Game</Title>
    <Description>Game flow, content and math primitives</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Salepate</Copyright>
    <PackageTags>Dirt.Framework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Log\Log.csproj" />
  </ItemGroup>

</Project>
