<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Dirt.GamePlugin</AssemblyName>
    <PackageId>Dirt.GamePlugin</PackageId>
    <Product>Dirt.GamePlugin</Product>
    <Version>1.1.0</Version>
    <Authors>Salepate</Authors>
    <Title>Dirt GamePlugin</Title>
    <Description>Game server plugin architecture with simulation routing</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Salepate</Copyright>
    <PackageTags>Dirt.Framework</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Mud\Server\Server.csproj" />
    <ProjectReference Include="..\Game\Game.csproj" />
    <ProjectReference Include="..\Log\Log.csproj" />
    <ProjectReference Include="..\Network\Network.csproj" />
    <ProjectReference Include="..\Simulation\Simulation.csproj" />
  </ItemGroup>

</Project>
