<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Dirt\Log\Log.csproj" />
    <ProjectReference Include="..\..\Dirt\Network\Network.csproj" />
    <ProjectReference Include="..\Dirt.Unity\Dirt.Unity.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy $(OutputPath) $(SolutionDir)\MMO.Client\Assets\Externals\Dirt\Plugins\ /i /y" />
  </Target>

</Project>
